### ISSUE TITLE
Evaluate Google Eventarc

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/gcloud-java#154]
Google recently [announced Eventarc in Preview](https://www.infoq.com/news/2020/11/eventarc-google-cloud-run/). See also [blog post](https://cloud.google.com/blog/products/serverless/build-event-driven-applications-in-cloud-run) with more details on this.

Key points of interest in relation to Eventarc:
  * Triggering events from 60+ Google Cloud products.
  * Orchestration of processing events. See “Eventarc in action” section in the [blog post](https://cloud.google.com/blog/products/serverless/build-event-driven-applications-in-cloud-run). It describes automated image processing pipeline.

As the result of this issue we need to have an analysis report which answers these questions:
 * Do we want to integrate or somehow otherwise use Eventarc?
 * What do we need to do to support [CloudEvents](https://cloudevents.io/) [specification](https://github.com/cloudevents/spec/blob/v1.0/spec.md) so that domain events declared in a Spine-based context can be consumed by non-Spine-based applications?

The [InfoQ article](https://www.infoq.com/news/2020/11/eventarc-google-cloud-run/) also mentions [CloudEvents SDK](https://github.com/cloudevents/sdk-csharp) and [Cloud Event library](https://github.com/googleapis/google-cloudevents) that are worth looking at.

**Comment by yuri-sergiichuk** [comment]
So I was playing with the Eventarc today and here's what I learned.


### Eventarc

Eventarc itself is a proprietary internal Google service that bootstraps a trigger to consume events from various Google services by a Cloud Run service.
Internally, it creates a Pub/Sub push subscription that receives GCP Audit Log events (e.g. `ApiKeyCreated` or `IAMRoleAssigned`) and pushes these events down to the Cloud Run service.

There is currently no way to extend Eventarc with some custom events and the proposed approach is just to use Pub/Sub to consume custom events using Eventarc triggers.

### CloudEvents

So how are CloudEvents related to the Eventarc and stuff? Basically, CloudEvents is a standard that defines what is the required structure of an event. It is required to have some CloudEvents-specific data fields like `specVersion` or `id`. But the actual event payload is not restricted by any terms.
If we want to produce valid CloudEvents we may just wrap our Spine events into a proper structure. And based on the destination transport there are different ways to do that "correctly". E.g. there's a Protobuf transport [release candidate](https://github.com/cloudevents/spec/blob/master/protobuf-format.md) that specifies the CloudEvent message, but the event data (payload) can be either binary, text, or Any.
