### ISSUE TITLE
Optimize `EventStore` Reads

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/gcloud-java#79]
Currently, to read an event stream with `EventStore`, we fetch all the entities and sort them in memory.

This behavior may be too inefficient for some use cases.

In order to optimize that, we may extend the Entity Column API with ordering.

**Comment by dmdashenkov** [comment]
@serhii-lekariev, ordering is now an implemented feature of entity columns. Please perform this optimization. This issue belongs more to `core-java` than to this repo.

**Comment by armiol** [comment]
Addressed in `2.0` snapshots.
