### ISSUE TITLE
`DsAggregateStorage` overwrites event count after last snapshot for different aggregates with the same ID

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/gcloud-java#90]
Now, `DsAggregateStorage`, overwrites an event count after the last snapshot for different aggregates with the same IDs.

The event count is stored in the `google.protobuf.Int32Value` kind. The ID of the count consists of `EVENTS_AFTER_SNAPSHOT_` prefix and a stringified value of an aggregate ID.

So, when two aggregates (e.g. `TaskRoot` and `TaskPart`) have the same ID (`task-123`), they have the same ID for the event count after the last snapshot.

To solve the problem, an ID of an event count should additionally contain a state type name of an aggregate. So, the ID should look like `EVENTS_AFTER_SNAPSHOT_foo.bar.StateType_task-123`.

The same problem exists for the aggregate lifecycle flags. Also, an ID of an aggregate lifecycle flags includes `EVENTS_AFTER_SNAPSHOT_` prefix, which is strange.

**Comment by dmdashenkov** [comment]
Fixed in #96.
