### ISSUE TITLE
`DsAggregateStorage` overwrites any previously created snapshot with a new one

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/gcloud-java#95]
Now, `DsAggregateStorage` overwrites any previously stored snapshot of a particular entity.

The record ID for a snapshot is generated using a static `SNAPSHOT` string concatenated with a stringified version of an entity ID. It means, that when it is time to store a new snapshot the Datastore record ID for the newly created snapshot is simply equal to the previously stored snapshot.

The desired behavior is to store multiple entity snapshots without actually overriding the previously-created ones.

**Comment by armiol** [comment]
Closing as resolved.
